added persian team members.
kubernetes/org pull request #2051
Opened 2020-07-21 04:26 UTC by sattarfeizollahibarough

Hi, This PR is added regarding the following PR:
https://github.com/kubernetes/website/pull/22565

2020-07-21 05:09 UTC, zacharysarah commented
/ok-to-test

2020-07-21 05:36 UTC, sattarfeizollahibarough commented
> 
> 
> @sattarfeizollahibarough: The following test **failed**, say `/retest` to rerun all failed tests:
> Test name 	Commit 	Details 	Rerun command
> pull-org-test-all 	[72aa9e9](https://github.com/kubernetes/org/commit/72aa9e9c73361fec11466b3a55b76e323cadf119) 	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/org/2051/pull-org-test-all/1285441883601899521) 	`/test pull-org-test-all`
> 
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes&repo=org&pr=2051). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3sattarfeizollahibarough). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/org/issues?q=is:issue+is:open) when you hit one in your PR.

In the log file mentioned that config_test.go failed. I should add the members into org.yaml file too.

2020-07-21 05:46 UTC, sattarfeizollahibarough commented
/retest

2020-07-21 17:28 UTC, zacharysarah commented
@sattarfeizollahibarough 👋 Thanks for your initiative. If I understand correctly, I think each team member needs to open their own [issue requesting membership in the kubernetes org](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E). 

In each issue:
1. Mention that you're starting a new localization for Persian
2. Assign a [SIG Docs chair or tech lead](https://github.com/kubernetes/community/tree/master/sig-docs#leadership) for approval `/assign <username>`

2020-07-22 04:46 UTC, sattarfeizollahibarough commented
> 
> 
> @sattarfeizollahibarough 👋 Thanks for your initiative. If I understand correctly, I think each team member needs to open their own [issue requesting membership in the Kubernetes org](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E).
> 
> In each issue:
> 
>     1. Mention that you're starting a new localization for Persian
> 
>     2. Assign a [SIG Docs chair or tech lead](https://github.com/kubernetes/community/tree/master/sig-docs#leadership) for approval `/assign <username>`

@zacharysarah , I have checked the Docs and it is mentioned that we should submit the request, However, our team does not have any sponsor from current members of the Kubernetes community 😕. And I also have a tremendous drive to contribute to the Kubernetes Docs.

2020-07-22 04:53 UTC, zacharysarah commented
@sattarfeizollahibarough I’m willing to sponsor you. Membership for new localizations is a well-established precedent.

2020-07-22 05:19 UTC, sattarfeizollahibarough commented
> 
> 
> @sattarfeizollahibarough I’m willing to sponsor you. Membership for new localizations is a well-established precedent.

@zacharysarah It's very kind of you to offer this and made me happy 😃 . As far as, it is mentioned in the submission form I need two sponsors. Is there someone else to offer such a generous offer?

2020-07-22 05:38 UTC, zacharysarah commented
> Is there someone else to offer such a generous offer?

@sftim @jimangel @celestehorgan 👋

2020-07-22 09:08 UTC, sftim commented
I'm happy to sponsor as well.

2020-07-22 09:36 UTC, sattarfeizollahibarough commented
> 
> 
> I'm happy to sponsor as well.

@sftim I really appreciate your help. So, I will submit my request.

2020-08-27 05:39 UTC, zacharysarah commented
/reopen

2020-09-16 14:27 UTC, kbhawkey commented
Is there remaining work to be done?

2020-10-02 06:59 UTC, nikhita commented
:wave: is this PR good to go?

2021-01-08 18:06 UTC, onlydole approved these changes
Thank you, @sattarfeizollahibarough! This looks good to me 👍🏼

2021-01-17 03:10 UTC, jimangel commented
/remove-lifecycle stale

2021-01-28 18:02 UTC, spiffxp requested changes
Needs rebase: these members are already in the org

2021-01-28 18:02 UTC, spiffxp commented on config/kubernetes/org.yaml
> +- FaezeAzimi
```suggestion
```

2021-01-28 18:02 UTC, spiffxp commented on config/kubernetes/org.yaml
> +- kasramp
```suggestion
```

2021-01-28 18:02 UTC, spiffxp commented on config/kubernetes/org.yaml
> +- sattarfeizollahibarough
```suggestion
```

2021-01-28 18:03 UTC, spiffxp commented
(this otherwise lgtm, please ping when resolved)

2021-01-28 18:08 UTC, sftim commented
Aside: the related PRs and issues for adding Persian seem to be turning stale.

2021-02-16 13:05 UTC, nikhita commented
Closing, please reopen if needed!

2021-02-16 13:05 UTC, closed without merging