add answer1991 to kubernetes/kubernetes member
kubernetes/org pull request #2178
Opened 2020-09-04 07:16 UTC by answer1991

Fixes #2165

2020-09-04 12:25 UTC, ameukam commented
/ok-to-test

2020-09-04 12:30 UTC, palnabarun requested changes

2020-09-04 12:30 UTC, palnabarun commented on config/kubernetes/org.yaml
>  - annajung
@answer1991 -- Can you sort the usernames like the following?
```suggestion
- annajung
- answer1991
```

2020-09-04 12:49 UTC, answer1991 commented
@palnabarun Fixed, PTAL

2020-09-04 12:52 UTC, ameukam commented
/lgtm

2020-09-04 13:11 UTC, palnabarun commented
Thank you @answer1991 :slightly_smiling_face: 

/lgtm

2020-09-07 12:45 UTC, mrbobbytables requested changes
One small nit, would you mind changing the commit message to: `Add answer1991 to kubernetes org`

kubernetes/kubernetes itself is a repo.^^;;;

2020-09-07 12:54 UTC, answer1991 commented
@mrbobbytables Done, thanks.

2020-09-08 09:25 UTC, nikhita approved these changes
/lgtm
/approve

2020-09-08 09:27 UTC, merged