Add mkumatag to milestone maintainers for test/images
kubernetes/org pull request #2198
Opened 2020-09-20 05:52 UTC by mkumatag

2020-09-20 05:54 UTC, mkumatag commented
/cc @justaugustus @nikhita

2020-09-22 17:16 UTC, justaugustus requested changes
@mkumatag -- One nit on the comment format.

I'm LGTM after that, but given that this is a SIG Testing directory, they should approve as well.
/hold
/assign @BenTheElder @spiffxp @stevekuznetsov

2020-09-22 17:16 UTC, justaugustus commented on config/kubernetes/sig-release/teams.yaml
> +    - mkumatag # test/images
```suggestion
    - mkumatag # Testing: test/images
```

2020-09-22 17:23 UTC, mkumatag commented on config/kubernetes/sig-release/teams.yaml
> +    - mkumatag # test/images
done!

2020-09-22 17:41 UTC, BenTheElder commented
FWIW I don't mind @mkumatag, but I feel we've been fairly available for this sort of thing and I'm not sure I like the precedent here, there are already a TON of people that can do this, if we start adding every directory approver I'm not sure what the point of the list is..?

2020-09-22 17:47 UTC, justaugustus commented
@BenTheElder -- we actually raised the meta topic on milestone-maintainers earlier today in the SIG Release meeting and @LappleApple has opened an issue to track --> https://github.com/kubernetes/sig-release/issues/1257

If you're happy with your current set of milestone maintainers, feel free to close this PR. :)

2020-09-22 17:55 UTC, mkumatag commented
> FWIW I don't mind @mkumatag, but I feel we've been fairly available for this sort of thing and I'm not sure I like the precedent here, there are already a TON of people that can do this, if we start adding every directory approver I'm not sure what the point of the list is..?

Make sense, closing this PR.

2020-09-22 17:55 UTC, closed without merging