Add dims as k8s maintainer
kubernetes/org pull request #2330
Opened 2020-11-12 20:50 UTC by dims

I was wondering why @derekwaynecarr was able to edit my PR to update a release note and i could not edit other's PR and found this group.

Also, we may need to prune this group at some point (cc @kubernetes/owners)

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

2020-11-12 21:06 UTC, ameukam commented
/lgtm

2020-11-12 21:07 UTC, justaugustus requested changes
@dims -- I'm actually surprised you weren't in one of the write access groups already!

In two separate commits, can you:
- Migrate this team to the SIG Release config subdirectory
- Add yourself in

Overall, we're trying to minimize the folks in `kubernetes-maintainers`, but that conversation with @spiffxp trailed off a while ago (ref: https://github.com/kubernetes/enhancements/issues/590).

That said, I do think you should be one of the folks in this group.
/hold for fixes

2020-11-12 23:47 UTC, cblecker commented
I have no issue adding dims to this group, albeit, it's legacy and we don't have a process for becoming a "maintainer" anymore.



> * Migrate this team to the SIG Release config subdirectory

@justaugustus What's your thought process behind giving sig-release control of this legacy group?

2020-11-13 02:20 UTC, dims commented
/assign @cblecker @spiffxp @mrbobbytables  

(adding more people for visibility)

2020-11-13 02:22 UTC, dims commented
@justaugustus i don't want to do that :) i am happy to wait until the discussion settles and would like the approvers to chime in.

2020-11-13 03:11 UTC, justaugustus commented
> @justaugustus What's your thought process behind giving sig-release control of this legacy group?

@cblecker -- Usually we'd put a `<repo>-maintainers` team within the SIG directory that owns it.
SIG Release cares about the content of the repo (and who has write access), but SIG Architecture approves repos in the `kubernetes` org, so really you could make a case for it living in either subdirectory.

This is more so for continued maintenance/eventual pruning of the group, without needing a top-level `/approve`.
(`milestone-maintainers` would be the parallel group that SIG Release maintains.)

2020-11-13 23:06 UTC, cblecker commented
> This is more so for continued maintenance/eventual pruning of the group, without needing a top-level `/approve`.

As this is a legacy group that no one sig technically owns, IMO I'm inclined to keep it with the @kubernetes/owners group.

2020-11-13 23:42 UTC, dims commented
i'd agree with you @cblecker

2020-11-13 23:44 UTC, justaugustus commented
Cool beans! :two_hearts: 
/lgtm

2020-11-14 00:04 UTC, savitharaghunathan reviewed
/lgtm

2020-11-14 00:24 UTC, palnabarun approved these changes
/lgtm

2020-11-14 01:43 UTC, dims commented
/hold cancel

thanks everyone!

2020-11-14 01:49 UTC, merged