Adding ams0 as a milestone maintainer
kubernetes/org pull request #2425
Opened 2021-01-15 17:34 UTC by ams0

/cc @kubernetes/release-team-leads
/cc @erismaster

2021-01-15 17:37 UTC, erismaster commented
/lgtm

Welcome!!

2021-01-15 19:02 UTC, soniasingla commented
#2426 is opened for access, once that PR has been closed, all the checks will get passed!

2021-01-15 19:14 UTC, palnabarun requested changes
@erismaster -- do you want to possibly add all the Bug Triage shadow in a single PR?

Also, the previous Bug Triage team needs to be removed if they don't need access.

2021-01-15 19:14 UTC, palnabarun commented on config/kubernetes/sig-release/teams.yaml
> +    - ams0 # Bug Triage Shadow for Kubernetes 1.21
```suggestion
    - ams0 # 1.21 Bug Triage Shadow
```

2021-01-15 19:14 UTC, palnabarun commented
/assign

2021-01-18 06:08 UTC, palnabarun commented
/hold for resolution on https://github.com/kubernetes/org/pull/2425#pullrequestreview-569548256

2021-01-18 06:13 UTC, erismaster commented
@palnabarun good call - I’ll get this reconciled tomorrow! We can probably close this one and #2424

2021-01-18 06:18 UTC, palnabarun commented
@erismaster -- Awesome! Thank you! :)

2021-01-18 06:19 UTC, palnabarun commented
@erismaster -- #2424 is fine. Daniel is added to the Kubernetes org now.

2021-01-18 06:20 UTC, palnabarun commented
/close

(ref: https://github.com/kubernetes/org/pull/2425#issuecomment-762008384)

2021-01-18 06:20 UTC, closed without merging