Add 1.21 Docs Shadows to GitHub teams
kubernetes/org pull request #2445
Opened 2021-01-19 21:36 UTC by reylejano

Add 1.21 Docs Shadows to milestone-maintainers and release-team GitHub teams

/assign @palnabarun @kikisdeliveryservice @savitharaghunathan @bai

/hold for feedback if shadows should be added to the milestone maintainers team. 
I think they should have the ability to add the 1.21 milestone on kubernetes/website PRs.

2021-01-19 21:51 UTC, savitharaghunathan requested changes

2021-01-19 21:51 UTC, savitharaghunathan commented on config/kubernetes/sig-release/teams.yaml
> +    - chandanim123 # 1.21 Docs Shadow
```suggestion
    + ChandaniM123 # 1.21 Docs Shadow
```

https://github.com/kubernetes/org/issues/2436 will be closed today via https://github.com/kubernetes/org/pull/2441

2021-01-19 21:51 UTC, savitharaghunathan commented on config/kubernetes/sig-release/teams.yaml
> +        - chandanim123 # 1.21 Docs Shadow
```suggestion
    + ChandaniM123 # 1.21 Docs Shadow
```

2021-01-19 21:57 UTC, savitharaghunathan commented on config/kubernetes/sig-release/teams.yaml
> +    - chandanim123 # 1.21 Docs Shadow
Also, please swap   
   - cheftako # Cloud Provider
   - chandanim123 # 1.21 Docs Shadow

2021-01-19 22:03 UTC, reylejano commented on config/kubernetes/sig-release/teams.yaml
> +        - chandanim123 # 1.21 Docs Shadow
Changes made and commits squashed

2021-01-19 22:04 UTC, reylejano commented
/retest

2021-01-19 22:11 UTC, reylejano commented
/retest

2021-01-20 01:15 UTC, savitharaghunathan reviewed
/lgtm

I agree with shadows having permissions to add/remove milestones. 

@reylejano please make sure that the handbook reflects this and add a cleanup step for the same. Thank you.

2021-01-20 01:17 UTC, reylejano commented
/hold cancel

2021-01-20 13:37 UTC, palnabarun reviewed
> if shadows should be added to the milestone maintainers team.

@reylejano -- I think access for adding/removing milestones on `k/website` is given through the `website-milestone-maintainers` group. Ref: https://github.com/kubernetes/org/blob/master/config/kubernetes/sig-docs/teams.yaml#L342

If the shadows don't need access to globally add/remove milestones, I think `website-milestone-maintainers` is the better place.

LMK what do you think.

/hold for resolution on the above

2021-01-20 15:10 UTC, reylejano commented
> > if shadows should be added to the milestone maintainers team.
> 
> @reylejano -- I think access for adding/removing milestones on `k/website` is given through the `website-milestone-maintainers` group. Ref: https://github.com/kubernetes/org/blob/master/config/kubernetes/sig-docs/teams.yaml#L342
> 
> If the shadows don't need access to globally add/remove milestones, I think `website-milestone-maintainers` is the better place.
> 
> LMK what do you think.
> 
> /hold for resolution on the above

@palnabarun I removed the shadows from the `milestone-maintners` and added them to `website-milestone-maintainers` in sig-docs/teams.yaml

2021-01-20 16:01 UTC, palnabarun commented
@reylejano -- Awesome! Thank you so much :)

/lgtm
/approve

2021-01-20 16:01 UTC, palnabarun commented
/hold cancel

2021-01-20 16:02 UTC, merged