convert github issue templates to forms
kubernetes/org pull request #2858
Opened 2021-08-02 12:49 UTC by mrbobbytables

Largely a no-op converting the issue templates to [GitHub Issue Forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)

Other changes include:
- Optional request in org membership form to take the LF [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
- Repo request form now has a checkbox explicitly asking if its a staging repo

Previews of what these forms look like are available here: https://github.com/mrbobbytables/issue-template-test/issues

/hold

2021-08-02 13:12 UTC, ameukam commented
/lgtm

2021-08-02 16:12 UTC, spiffxp requested changes
One nit, otherwise LGTM

2021-08-02 16:12 UTC, spiffxp commented on .github/ISSUE_TEMPLATE/general-support.yml
> +    render: markdown
This ends up dumping text
```
in a preformatted box that doesn't do word wrapping at all
```
```suggestion
```

2021-08-02 16:59 UTC, mrbobbytables commented on .github/ISSUE_TEMPLATE/general-support.yml
> +    render: markdown
done 👍

2021-08-02 19:22 UTC, ameukam commented
/lgtm
/hold
Remove hold when ready

2021-08-03 12:08 UTC, mrbobbytables commented
/hold cancel

2021-08-03 12:08 UTC, merged