Add 1.26 RT Shadows
kubernetes/org pull request #3686
Opened 2022-09-13 22:17 UTC by leonardpahlke

Signed-off-by: leonardpahlke <leonard.pahlke@googlemail.com>

Add 1.26 RT Shadows

cc @kubernetes/release-team-leads @palnabarun

2022-09-13 22:27 UTC, reylejano commented on config/kubernetes/sig-release/teams.yaml
> +        - mickeyboxell # 1.26 Comms Shadow
```suggestion
        - mickeyboxell # 1.26 Docs Shadow
```

2022-09-14 12:16 UTC, fsmunoz requested changes

2022-09-14 12:16 UTC, fsmunoz commented on config/kubernetes/sig-release/teams.yaml
> +        - bradmccoydev # 1.26 Comms Lead
Should be "Comms Shadow"

2022-09-14 12:16 UTC, fsmunoz commented on config/kubernetes/sig-release/teams.yaml
> +        - davidmirror-ops # 1.26 Comms Lead
Should be "Comms Shadow"

2022-09-14 12:16 UTC, fsmunoz commented on config/kubernetes/sig-release/teams.yaml
> +        - Debanitrkl # 1.26 Comms Lead
Should be "Comms Shadow"

2022-09-14 14:33 UTC, palnabarun commented
We have 3 shadows pending to be added to the org.
```
    config_test.go:272: The following members of team release-team are not Kubernetes org members: heshamaboelmagd, neoaggelos, subhasmitasw
    config_test.go:272: The team release-team in org Kubernetes has an unsorted list of members 
```

2022-09-20 19:50 UTC, palnabarun commented
Once https://github.com/kubernetes/org/pull/3708 merges, the remaining members would need to accept the org invitation request. And then this PR should be 🟢.

2022-09-20 20:50 UTC, reylejano commented
/test pull-org-test-all

2022-09-20 20:55 UTC, reylejano commented on config/kubernetes/sig-release/teams.yaml
> +        - bradmccoydev # 1.26 Comms Shadow
pull-org-test-all test is failing due to these entries are not sorted
please move the members starting with the letter b before the members starting with the letter c
```suggestion
        - bharitwal # 1.26 CI Signal Shadow
        - bradmccoydev # 1.26 Comms Shadow
```

2022-09-21 09:01 UTC, leonardpahlke commented
Thanks, @palnabarun @reylejano and @fsmunoz for your reviews :) Now it looks like the PR is finally ready to get merged

2022-09-21 09:02 UTC, leonardpahlke commented
/label tide/merge-method-squash

2022-09-21 09:24 UTC, palnabarun approved these changes
/lgtm
/approve

2022-09-21 09:24 UTC, merged