Add 1.28 team member to sig-release YAML
kubernetes/org pull request #4210
Opened 2023-05-11 16:28 UTC by gracenng

As part of 1.28 release cycle commencing. Find 1.28 release team members [here](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.28/release-team.md)

As discussed with @furkatgofurov7, we will not add bug triage shadows to `milestone-maintainers` until we find out where they'll need it.

cc @kubernetes/sig-release-leads @leonardpahlke

2023-05-15 10:24 UTC, furkatgofurov7 commented
> > As discussed with @furkatgofurov7, we will not add bug triage shadows to milestone-maintainers until we find out where they'll need it.
> 
> +1, this was not required on the 1.27 cycle

Thanks for confirming @neoaggelos.

2023-05-16 17:02 UTC, leonardpahlke approved these changes
/lgtm

2023-05-17 06:44 UTC, saschagrunert approved these changes

2023-05-17 06:45 UTC, saschagrunert requested changes
Ah yeah let's fix that before:
```
config_test.go:272: The following members of team milestone-maintainers are not Kubernetes org members: kasambx, salehsedghpour
    config_test.go:272: The following members of team release-team are not Kubernetes org members: hailkomputer, kasambx, moficodes, salehsedghpour, zelenushechka
    config_test.go:272: The following members of team release-team-docs are not Kubernetes org members: adminturneddevops, vibhorchinda
    config_test.go:272: The following members of team release-team-enhancements are not Kubernetes org members: kasambx, salehsedghpour
    config_test.go:272: The following members of team release-team-release-notes are not Kubernetes org members: muddapu, rashansmith
    config_test.go:272: The following members of team ci-signal are not Kubernetes org members: amotul-raheem, mansikulkarni96
    config_test.go:272: The following members of team release-team-bug-triage are not Kubernetes org members: hailkomputer, moficodes, zelenushechka
    config_test.go:272: The following members of team release-team-comms are not Kubernetes org members: krol, mashby2022, thschue
```

2023-05-18 17:09 UTC, Atharva-Shinde commented
/retest

2023-05-23 20:03 UTC, gracenng commented
/retest

2023-05-24 13:44 UTC, gracenng commented
Pending https://github.com/kubernetes/org/pull/4246

2023-05-24 16:22 UTC, gracenng commented
/retest

2023-05-24 16:48 UTC, palnabarun commented
/lgtm

/hold for SIG Release Lead to approve this

2023-05-25 06:48 UTC, saschagrunert approved these changes
/unhold

2023-05-25 06:50 UTC, merged