Peribolos: add repo perms for kube-scheduler-wasm-extension team
kubernetes/org pull request #4370
Opened 2023-08-07 06:51 UTC by Priyankasaggu11929

The PR update the `kube-scheduler-wasm-extension-admins` team to provide admin access to the [kube-scheduler-wasm-extension](https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension) repo.

/area github-repo
/assign @MadhavJivrajani

2023-08-09 13:36 UTC, Priyankasaggu11929 commented
Hello @jayunit100 – could you please confirm whether [sig-windows-dev-tools-admins](https://github.com/kubernetes/org/blob/a7ec3121cce710d822e329365270dd5b942e4437/config/kubernetes-sigs/sig-windows/teams.yaml#L46-L57) GH team requires additional `admin` access for the [k-sigs/windows-service-proxy](https://github.com/kubernetes-sigs/windows-service-proxy) repository (besides, the existing `admin` access to [k-sigs/sig-windows-dev-tools](https://github.com/kubernetes-sigs/sig-windows-dev-tools) repo)?

If so, I'll update the teams config accordingly to reflect the additional repo permissions. Thanks!

2023-08-09 13:40 UTC, MadhavJivrajani reviewed
Just one comment apart from the last bit of inconsistencies being discussed being on slack: 
https://kubernetes.slack.com/archives/C01672LSZL0/p1691582605843739

2023-08-09 13:49 UTC, Priyankasaggu11929 commented
Hello @jacobwolfaws – could you please confirm if the current config mapping for **[aws-fsx-csi-driver-admins](https://github.com/kubernetes/org/blob/main/config/kubernetes-sigs/sig-aws/teams.yaml#L55-L66)**  and **[aws-fsx-csi-driver-maintainers](https://github.com/kubernetes/org/blob/main/config/kubernetes-sigs/sig-aws/teams.yaml#L67-L79)** GH teams, granting `admin` access to **[k-sigs/aws-fsx-csi-driver](https://github.com/kubernetes-sigs/aws-fsx-csi-driver)** repo is correct?

**_OR_** the ^ teams repo permissions needs to be updated to – `admin` access to **[k-sigs/aws-fsx-openzfs-csi-driver](https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver)** repo? Thanks!

2023-08-09 13:53 UTC, jayunit100 commented
yes , can we also add @aroradaman to the windows-service-proxy owners team thanks !

2023-08-09 13:57 UTC, Priyankasaggu11929 commented
Hello @logicalhan – could you please confirm if the current repo permissions mapping for **[instrumentation-admins](https://github.com/kubernetes/org/blob/de341ff702383b457c11ce94df3c85befb0bd4ed/config/kubernetes-sigs/sig-instrumentation/teams.yaml#L16-L25)** GH team, granting `admin` access to **[k-sigs/instrumentation](https://github.com/kubernetes-sigs/instrumentation)** repo is correct?

**_OR_** the team repo permissions needs to be updated to – `admin` access to **[k-sigs/intrumentation-addons](https://github.com/kubernetes-sigs/instrumentation-addons)** repo? Thanks!

2023-08-09 14:05 UTC, logicalhan commented
> Hello @logicalhan – could you please confirm if the current repo permissions mapping for **[instrumentation-admins](https://github.com/kubernetes/org/blob/de341ff702383b457c11ce94df3c85befb0bd4ed/config/kubernetes-sigs/sig-instrumentation/teams.yaml#L16-L25)** GH team, granting `admin` access to **[k-sigs/instrumentation](https://github.com/kubernetes-sigs/instrumentation)** repo is correct?

Yes, it looks okay to me. Thanks!

2023-08-09 14:11 UTC, Priyankasaggu11929 commented on config/kubernetes-sigs/sig-contributor-experience/teams.yaml
> +       sigs-github-actions: write
@MadhavJivrajani, updated in the latest commit refresh. Thanks!

2023-08-09 14:23 UTC, jacobwolfaws commented
> Hello @jacobwolfaws – could you please confirm if the current repo permissions mapping for **[aws-fsx-csi-driver-admins](https://github.com/kubernetes/org/blob/main/config/kubernetes-sigs/sig-aws/teams.yaml#L55-L66)** and **[aws-fsx-csi-driver-maintainers](https://github.com/kubernetes/org/blob/main/config/kubernetes-sigs/sig-aws/teams.yaml#L67-L79)** GH teams, granting `admin` access to **[k-sigs/aws-fsx-csi-driver](https://github.com/kubernetes-sigs/aws-fsx-csi-driver)** repo is correct?
> 
> **_OR_** the ^ teams repo permissions needs to be updated to – `admin` access to **[k-sigs/aws-fsx-openzfs-csi-driver](https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver)** repo? Thanks!



> Hello @jacobwolfaws – could you please confirm if the current repo permissions mapping for **[aws-fsx-csi-driver-admins](https://github.com/kubernetes/org/blob/main/config/kubernetes-sigs/sig-aws/teams.yaml#L55-L66)** and **[aws-fsx-csi-driver-maintainers](https://github.com/kubernetes/org/blob/main/config/kubernetes-sigs/sig-aws/teams.yaml#L67-L79)** GH teams, granting `admin` access to **[k-sigs/aws-fsx-csi-driver](https://github.com/kubernetes-sigs/aws-fsx-csi-driver)** repo is correct?
> 
> **_OR_** the ^ teams repo permissions needs to be updated to – `admin` access to **[k-sigs/aws-fsx-openzfs-csi-driver](https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver)** repo? Thanks!

Those look right to me, openzfs has separate permissions defined in another file.

2023-08-09 14:31 UTC, Priyankasaggu11929 commented
Thanks for the confirmation @jacobwolfaws.

@MadhavJivrajani, the PR is ready for another round of review. Thanks!

2023-08-10 11:50 UTC, MadhavJivrajani commented on config/kubernetes-sigs/sig-windows/teams.yaml
Leaving breadcrumbs in case anyone wants to see why this addition was done:
Reason for addition here: https://github.com/kubernetes/org/pull/4370#issuecomment-1671371021

2023-08-10 12:10 UTC, MadhavJivrajani requested changes
@Priyankasaggu11929 a few more inconsistencies:
- `kubernetes/sig-architecture-leads` needs **admin** access to repo `kubernetes/design-proposals-archive` (ref https://github.com/kubernetes/community/issues/6055)
- `kubernetes/registry.k8s.io-admins` needs  **admin** access to repo `kubernetes/registry.k8s.io`
- `kubernetes/registry.k8s.io-maintainers` needs **write** access to repo `kubernetes/registry.k8s.io`

From the list share don slack: https://kubernetes.slack.com/archives/C01672LSZL0/p1691583200807829?thread_ts=1691582605.843739&cid=C01672LSZL0

2023-08-10 12:41 UTC, Priyankasaggu11929 commented
In response to https://github.com/kubernetes/org/pull/4370#pullrequestreview-1571736892:

@MadhavJivrajani – added the missing repo perms  in the latest 2 commits. PTAL again. Thanks! :pray:

2023-08-10 16:38 UTC, MadhavJivrajani approved these changes
/lgtm 
/approve

2023-08-15 11:49 UTC, MadhavJivrajani approved these changes
/lgtm
/hold cancel

2023-08-15 11:53 UTC, merged