add mlavacca as ingress2gateway maintainer
kubernetes/org pull request #4862
Opened 2024-04-02 13:33 UTC by LiorLieberman

As discussed offline, we are adding Mattia as ingress2gateway maintainer

/cc @shaneutt @robscott @youngnick @mlavacca

2024-04-02 13:51 UTC, shaneutt commented
Looks good. While you're in here, please feel free to move me to `emeritus`.

2024-04-02 21:20 UTC, robscott commented
LGTM, thanks @mlavacca and @LiorLieberman!

We should probably also move Bowei to emeritus.

2024-04-03 06:23 UTC, LiorLieberman commented
Removed from here and added `emeriturs_approvers` on ingress2gateway OWNERS - https://github.com/kubernetes-sigs/ingress2gateway/pull/149

2024-04-03 11:52 UTC, shaneutt requested changes

2024-04-03 11:52 UTC, shaneutt commented on config/kubernetes-sigs/sig-network/teams.yaml
> -    - shaneutt
You've _removed_ previous maintainers, what we do instead is we'll add a section called `emeritus` which doesn't carry any official position but denotes previously involved maintainers.

2024-04-03 11:53 UTC, shaneutt approved these changes
/approve

2024-04-03 11:54 UTC, shaneutt commented
/assign @thockin

2024-04-03 15:28 UTC, thockin commented
/lgtm
/approve

2024-04-03 15:32 UTC, merged